swagger: '2.0'
info:
  title: longtimeacces
  x-ibm-name: longtimeacces
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
  servers:
    - url: https://openapi.taxes.gov.il/shaam/tsandbox/longtimeacces
      description: ''
      type:
        - production
        - development
  oauth-servers:
    Oauth:
      tokenUrls:
        - https://openapi.taxes.gov.il/shaam/tsandbox/longtimetoken/oauth2/token
      authorizationUrls:
        - https://openapi.taxes.gov.il/shaam/tsandbox/longtimetoken/oauth2/authorize
      refreshUrls: []
basePath: /shaam/tsandbox/longtimeacces
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  Oauth:
    type: oauth2
    x-ibm-oauth-provider: longtimetoken
    flow: accessCode
    authorizationUrl: /longtimetoken/oauth2/authorize
    tokenUrl: /longtimetoken/oauth2/token
    scopes:
      scope: Shaam scope
  untitled:
    type: oauth2
    x-ibm-oauth-provider: shorttimetoken
    flow: accessCode
    authorizationUrl: /shorttimetoken/oauth2/authorize
    tokenUrl: /shorttimetoken/oauth2/token
    scopes:
      scope: Shaam scope
security:
  - Oauth:
      - scope
schemes:
  - https
host: openapi.taxes.gov.il
