swagger: '2.0'
info:
  title: onetimeaccess
  x-ibm-name: onetimeaccess
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
  servers:
    - url: https://openapi.taxes.gov.il/shaam/tsandbox/onetimeaccess
      description: ''
      type:
        - production
        - development
  oauth-servers:
    onetime:
      tokenUrls:
        - https://openapi.taxes.gov.il/shaam/tsandbox/onetimetoken/oauth2/token
      authorizationUrls:
        - https://openapi.taxes.gov.il/shaam/tsandbox/onetimetoken/oauth2/authorize
      refreshUrls: []
basePath: /shaam/tsandbox/onetimeaccess
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  onetime:
    type: oauth2
    x-ibm-oauth-provider: onetimetoken
    flow: accessCode
    authorizationUrl: /onetimetoken/oauth2/authorize
    tokenUrl: /onetimetoken/oauth2/token
    scopes:
      scope: Shaam scope
security:
  - onetime: []
schemes:
  - https
host: openapi.taxes.gov.il
