swagger: '2.0'
info:
  title: openAccess
  x-ibm-name: openaccess
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
  servers:
    - url: https://openapi.taxes.gov.il/shaam/tsandbox/openaccess
      description: ''
      type:
        - production
        - development
basePath: /shaam/tsandbox/openaccess
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions: {}
security: []
schemes:
  - https
host: openapi.taxes.gov.il
