-- Identity Jumping 1000 – IDENTITY_CACHE 

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = OFF

CREATE TABLE TEMP(Id INT IDENTITY(1,1), [Name] NCHAR(1))
INSERT INTO TEMP VALUES('A'), ('B')
INSERT INTO TEMP VALUES('C'), ('D')
 
SELECT * FROM TEMP

DBCC CHECKIDENT ('TEMP', RESEED, 6)

INSERT INTO TEMP VALUES('E'), ('F')

/*
	Id	Name
	1	A
	2	B
	3	C
	4	D
	7	E
	8	F
*/